-- Daily learning digest: one row per day summarizing what the user learned,
-- generated by the cron from that day's quiz questions + their results.
create table if not exists daily_learning (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  learn_date date not null,
  summary text not null,             -- markdown recap of the day's learning
  concepts text[] default '{}',      -- concept tags covered
  score int,                         -- quiz score that day
  total int,                         -- quiz total that day
  created_at timestamptz not null default now(),
  unique (user_id, learn_date)
);
create index if not exists daily_learning_user_idx on daily_learning(user_id, learn_date desc);

alter table daily_learning enable row level security;
create policy "own daily_learning" on daily_learning for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);
