import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

export const runtime = "nodejs";

// POST -> idempotent first-run setup: ensure a baseline learner_profile exists,
// and seed the 12 skills so the dashboard/plan have something to work with.
// The real curriculum is generated by /api/plan (called by the client if empty).
export async function POST() {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "unauthorized" }, { status: 401 });

  // Baseline learner profile (only if none yet).
  const { data: prof } = await supabase
    .from("learner_profile")
    .select("user_id")
    .eq("user_id", user.id)
    .maybeSingle();
  if (!prof) {
    await supabase.from("learner_profile").insert({
      user_id: user.id,
      narrative:
        "New learner — Butler is still assessing. Complete a few daily sessions and this profile will fill in with your real strengths, gaps, and how you think.",
      strengths: [],
      gaps: [],
    });
  }

  const { data: plan } = await supabase
    .from("curriculum")
    .select("id")
    .eq("user_id", user.id)
    .limit(1);
  const needsPlan = !plan || plan.length === 0;

  return NextResponse.json({ ok: true, needsPlan });
}
